package neo;

import com.google.common.collect.Sets;
import java.util.Set;
import javax.annotation.Nullable;
import net.minecraft.util.ResourceLocation;

public class Nk {
   private static final Set<co> CACHE;
   public static final co AIR;
   public static final co STONE;
   public static final ec GRASS;
   public static final co DIRT;
   public static final co COBBLESTONE;
   public static final co PLANKS;
   public static final co SAPLING;
   public static final co BEDROCK;
   public static final dx FLOWING_WATER;
   public static final gW WATER;
   public static final dx FLOWING_LAVA;
   public static final gW LAVA;
   public static final gk SAND;
   public static final co GRAVEL;
   public static final co GOLD_ORE;
   public static final co IRON_ORE;
   public static final co COAL_ORE;
   public static final co LOG;
   public static final co LOG2;
   public static final ew LEAVES;
   public static final ew LEAVES2;
   public static final co SPONGE;
   public static final co GLASS;
   public static final co LAPIS_ORE;
   public static final co LAPIS_BLOCK;
   public static final co DISPENSER;
   public static final co SANDSTONE;
   public static final co NOTEBLOCK;
   public static final co BED;
   public static final co GOLDEN_RAIL;
   public static final co DETECTOR_RAIL;
   public static final ff STICKY_PISTON;
   public static final co WEB;
   public static final hk TALLGRASS;
   public static final dg DEADBUSH;
   public static final ff PISTON;
   public static final fi PISTON_HEAD;
   public static final co WOOL;
   public static final fj PISTON_EXTENSION;
   public static final dS YELLOW_FLOWER;
   public static final dS RED_FLOWER;
   public static final cI BROWN_MUSHROOM;
   public static final cI RED_MUSHROOM;
   public static final co GOLD_BLOCK;
   public static final co IRON_BLOCK;
   public static final gG DOUBLE_STONE_SLAB;
   public static final gG STONE_SLAB;
   public static final co BRICK_BLOCK;
   public static final co TNT;
   public static final co BOOKSHELF;
   public static final co MOSSY_COBBLESTONE;
   public static final co OBSIDIAN;
   public static final co TORCH;
   public static final dN FIRE;
   public static final co MOB_SPAWNER;
   public static final co OAK_STAIRS;
   public static final cT CHEST;
   public static final gf REDSTONE_WIRE;
   public static final co DIAMOND_ORE;
   public static final co DIAMOND_BLOCK;
   public static final co CRAFTING_TABLE;
   public static final co WHEAT;
   public static final co FARMLAND;
   public static final co FURNACE;
   public static final co LIT_FURNACE;
   public static final co STANDING_SIGN;
   public static final do OAK_DOOR;
   public static final do SPRUCE_DOOR;
   public static final do BIRCH_DOOR;
   public static final do JUNGLE_DOOR;
   public static final do ACACIA_DOOR;
   public static final do DARK_OAK_DOOR;
   public static final co LADDER;
   public static final co RAIL;
   public static final co STONE_STAIRS;
   public static final co WALL_SIGN;
   public static final co LEVER;
   public static final co STONE_PRESSURE_PLATE;
   public static final do IRON_DOOR;
   public static final co WOODEN_PRESSURE_PLATE;
   public static final co REDSTONE_ORE;
   public static final co LIT_REDSTONE_ORE;
   public static final co UNLIT_REDSTONE_TORCH;
   public static final co REDSTONE_TORCH;
   public static final co STONE_BUTTON;
   public static final co SNOW_LAYER;
   public static final co ICE;
   public static final co SNOW;
   public static final cN CACTUS;
   public static final co CLAY;
   public static final gg REEDS;
   public static final co JUKEBOX;
   public static final co OAK_FENCE;
   public static final co SPRUCE_FENCE;
   public static final co BIRCH_FENCE;
   public static final co JUNGLE_FENCE;
   public static final co DARK_OAK_FENCE;
   public static final co ACACIA_FENCE;
   public static final co PUMPKIN;
   public static final co NETHERRACK;
   public static final co SOUL_SAND;
   public static final co GLOWSTONE;
   public static final fo PORTAL;
   public static final co LIT_PUMPKIN;
   public static final co CAKE;
   public static final ga UNPOWERED_REPEATER;
   public static final ga POWERED_REPEATER;
   public static final co TRAPDOOR;
   public static final co MONSTER_EGG;
   public static final co STONEBRICK;
   public static final co BROWN_MUSHROOM_BLOCK;
   public static final co RED_MUSHROOM_BLOCK;
   public static final co IRON_BARS;
   public static final co GLASS_PANE;
   public static final co MELON_BLOCK;
   public static final co PUMPKIN_STEM;
   public static final co MELON_STEM;
   public static final co VINE;
   public static final co OAK_FENCE_GATE;
   public static final co SPRUCE_FENCE_GATE;
   public static final co BIRCH_FENCE_GATE;
   public static final co JUNGLE_FENCE_GATE;
   public static final co DARK_OAK_FENCE_GATE;
   public static final co ACACIA_FENCE_GATE;
   public static final co BRICK_STAIRS;
   public static final co STONE_BRICK_STAIRS;
   public static final eJ MYCELIUM;
   public static final co WATERLILY;
   public static final co NETHER_BRICK;
   public static final co NETHER_BRICK_FENCE;
   public static final co NETHER_BRICK_STAIRS;
   public static final co NETHER_WART;
   public static final co ENCHANTING_TABLE;
   public static final co BREWING_STAND;
   public static final cR CAULDRON;
   public static final co END_PORTAL;
   public static final co END_PORTAL_FRAME;
   public static final co END_STONE;
   public static final co DRAGON_EGG;
   public static final co REDSTONE_LAMP;
   public static final co LIT_REDSTONE_LAMP;
   public static final gG DOUBLE_WOODEN_SLAB;
   public static final gG WOODEN_SLAB;
   public static final co COCOA;
   public static final co SANDSTONE_STAIRS;
   public static final co EMERALD_ORE;
   public static final co ENDER_CHEST;
   public static final hv TRIPWIRE_HOOK;
   public static final co TRIPWIRE;
   public static final co EMERALD_BLOCK;
   public static final co SPRUCE_STAIRS;
   public static final co BIRCH_STAIRS;
   public static final co JUNGLE_STAIRS;
   public static final co COMMAND_BLOCK;
   public static final cA BEACON;
   public static final co COBBLESTONE_WALL;
   public static final co FLOWER_POT;
   public static final co CARROTS;
   public static final co POTATOES;
   public static final co WOODEN_BUTTON;
   public static final gE SKULL;
   public static final co ANVIL;
   public static final co TRAPPED_CHEST;
   public static final co LIGHT_WEIGHTED_PRESSURE_PLATE;
   public static final co HEAVY_WEIGHTED_PRESSURE_PLATE;
   public static final fW UNPOWERED_COMPARATOR;
   public static final fW POWERED_COMPARATOR;
   public static final df DAYLIGHT_DETECTOR;
   public static final df DAYLIGHT_DETECTOR_INVERTED;
   public static final co REDSTONE_BLOCK;
   public static final co QUARTZ_ORE;
   public static final em HOPPER;
   public static final co QUARTZ_BLOCK;
   public static final co QUARTZ_STAIRS;
   public static final co ACTIVATOR_RAIL;
   public static final co DROPPER;
   public static final co STAINED_HARDENED_CLAY;
   public static final co BARRIER;
   public static final co IRON_TRAPDOOR;
   public static final co HAY_BLOCK;
   public static final co CARPET;
   public static final co HARDENED_CLAY;
   public static final co COAL_BLOCK;
   public static final co PACKED_ICE;
   public static final co ACACIA_STAIRS;
   public static final co DARK_OAK_STAIRS;
   public static final co SLIME_BLOCK;
   public static final dr DOUBLE_PLANT;
   public static final gN STAINED_GLASS;
   public static final gP STAINED_GLASS_PANE;
   public static final co PRISMARINE;
   public static final co SEA_LANTERN;
   public static final co STANDING_BANNER;
   public static final co WALL_BANNER;
   public static final co RED_SANDSTONE;
   public static final co RED_SANDSTONE_STAIRS;
   public static final gG DOUBLE_STONE_SLAB2;
   public static final gG STONE_SLAB2;
   public static final co END_ROD;
   public static final co CHORUS_PLANT;
   public static final co CHORUS_FLOWER;
   public static final co PURPUR_BLOCK;
   public static final co PURPUR_PILLAR;
   public static final co PURPUR_STAIRS;
   public static final gG PURPUR_DOUBLE_SLAB;
   public static final gG PURPUR_SLAB;
   public static final co END_BRICKS;
   public static final co BEETROOTS;
   public static final co GRASS_PATH;
   public static final co END_GATEWAY;
   public static final co REPEATING_COMMAND_BLOCK;
   public static final co CHAIN_COMMAND_BLOCK;
   public static final co FROSTED_ICE;
   public static final co MAGMA;
   public static final co NETHER_WART_BLOCK;
   public static final co RED_NETHER_BRICK;
   public static final co BONE_BLOCK;
   public static final co STRUCTURE_VOID;
   public static final co OBSERVER;
   public static final co WHITE_SHULKER_BOX;
   public static final co ORANGE_SHULKER_BOX;
   public static final co MAGENTA_SHULKER_BOX;
   public static final co LIGHT_BLUE_SHULKER_BOX;
   public static final co YELLOW_SHULKER_BOX;
   public static final co LIME_SHULKER_BOX;
   public static final co PINK_SHULKER_BOX;
   public static final co GRAY_SHULKER_BOX;
   public static final co SILVER_SHULKER_BOX;
   public static final co CYAN_SHULKER_BOX;
   public static final co PURPLE_SHULKER_BOX;
   public static final co BLUE_SHULKER_BOX;
   public static final co BROWN_SHULKER_BOX;
   public static final co GREEN_SHULKER_BOX;
   public static final co RED_SHULKER_BOX;
   public static final co BLACK_SHULKER_BOX;
   public static final co WHITE_GLAZED_TERRACOTTA;
   public static final co ORANGE_GLAZED_TERRACOTTA;
   public static final co MAGENTA_GLAZED_TERRACOTTA;
   public static final co LIGHT_BLUE_GLAZED_TERRACOTTA;
   public static final co YELLOW_GLAZED_TERRACOTTA;
   public static final co LIME_GLAZED_TERRACOTTA;
   public static final co PINK_GLAZED_TERRACOTTA;
   public static final co GRAY_GLAZED_TERRACOTTA;
   public static final co SILVER_GLAZED_TERRACOTTA;
   public static final co CYAN_GLAZED_TERRACOTTA;
   public static final co PURPLE_GLAZED_TERRACOTTA;
   public static final co BLUE_GLAZED_TERRACOTTA;
   public static final co BROWN_GLAZED_TERRACOTTA;
   public static final co GREEN_GLAZED_TERRACOTTA;
   public static final co RED_GLAZED_TERRACOTTA;
   public static final co BLACK_GLAZED_TERRACOTTA;
   public static final co CONCRETE;
   public static final co CONCRETE_POWDER;
   public static final co STRUCTURE_BLOCK;

   public Nk() {
   }

   @Nullable
   private static co getRegisteredBlock(String blockName) {
      co block = (co)co.REGISTRY.getObject(new ResourceLocation(blockName));
      if (!CACHE.add(block)) {
         throw new IllegalStateException("Invalid Block requested: " + blockName);
      } else {
         return block;
      }
   }

   static {
      if (!NI.isRegistered()) {
         throw new RuntimeException("Accessed Blocks before Bootstrap!");
      } else {
         CACHE = Sets.newHashSet();
         AIR = getRegisteredBlock("air");
         STONE = getRegisteredBlock("stone");
         GRASS = (ec)getRegisteredBlock("grass");
         DIRT = getRegisteredBlock("dirt");
         COBBLESTONE = getRegisteredBlock("cobblestone");
         PLANKS = getRegisteredBlock("planks");
         SAPLING = getRegisteredBlock("sapling");
         BEDROCK = getRegisteredBlock("bedrock");
         FLOWING_WATER = (dx)getRegisteredBlock("flowing_water");
         WATER = (gW)getRegisteredBlock("water");
         FLOWING_LAVA = (dx)getRegisteredBlock("flowing_lava");
         LAVA = (gW)getRegisteredBlock("lava");
         SAND = (gk)getRegisteredBlock("sand");
         GRAVEL = getRegisteredBlock("gravel");
         GOLD_ORE = getRegisteredBlock("gold_ore");
         IRON_ORE = getRegisteredBlock("iron_ore");
         COAL_ORE = getRegisteredBlock("coal_ore");
         LOG = getRegisteredBlock("log");
         LOG2 = getRegisteredBlock("log2");
         LEAVES = (ew)getRegisteredBlock("leaves");
         LEAVES2 = (ew)getRegisteredBlock("leaves2");
         SPONGE = getRegisteredBlock("sponge");
         GLASS = getRegisteredBlock("glass");
         LAPIS_ORE = getRegisteredBlock("lapis_ore");
         LAPIS_BLOCK = getRegisteredBlock("lapis_block");
         DISPENSER = getRegisteredBlock("dispenser");
         SANDSTONE = getRegisteredBlock("sandstone");
         NOTEBLOCK = getRegisteredBlock("noteblock");
         BED = getRegisteredBlock("bed");
         GOLDEN_RAIL = getRegisteredBlock("golden_rail");
         DETECTOR_RAIL = getRegisteredBlock("detector_rail");
         STICKY_PISTON = (ff)getRegisteredBlock("sticky_piston");
         WEB = getRegisteredBlock("web");
         TALLGRASS = (hk)getRegisteredBlock("tallgrass");
         DEADBUSH = (dg)getRegisteredBlock("deadbush");
         PISTON = (ff)getRegisteredBlock("piston");
         PISTON_HEAD = (fi)getRegisteredBlock("piston_head");
         WOOL = getRegisteredBlock("wool");
         PISTON_EXTENSION = (fj)getRegisteredBlock("piston_extension");
         YELLOW_FLOWER = (dS)getRegisteredBlock("yellow_flower");
         RED_FLOWER = (dS)getRegisteredBlock("red_flower");
         BROWN_MUSHROOM = (cI)getRegisteredBlock("brown_mushroom");
         RED_MUSHROOM = (cI)getRegisteredBlock("red_mushroom");
         GOLD_BLOCK = getRegisteredBlock("gold_block");
         IRON_BLOCK = getRegisteredBlock("iron_block");
         DOUBLE_STONE_SLAB = (gG)getRegisteredBlock("double_stone_slab");
         STONE_SLAB = (gG)getRegisteredBlock("stone_slab");
         BRICK_BLOCK = getRegisteredBlock("brick_block");
         TNT = getRegisteredBlock("tnt");
         BOOKSHELF = getRegisteredBlock("bookshelf");
         MOSSY_COBBLESTONE = getRegisteredBlock("mossy_cobblestone");
         OBSIDIAN = getRegisteredBlock("obsidian");
         TORCH = getRegisteredBlock("torch");
         FIRE = (dN)getRegisteredBlock("fire");
         MOB_SPAWNER = getRegisteredBlock("mob_spawner");
         OAK_STAIRS = getRegisteredBlock("oak_stairs");
         CHEST = (cT)getRegisteredBlock("chest");
         REDSTONE_WIRE = (gf)getRegisteredBlock("redstone_wire");
         DIAMOND_ORE = getRegisteredBlock("diamond_ore");
         DIAMOND_BLOCK = getRegisteredBlock("diamond_block");
         CRAFTING_TABLE = getRegisteredBlock("crafting_table");
         WHEAT = getRegisteredBlock("wheat");
         FARMLAND = getRegisteredBlock("farmland");
         FURNACE = getRegisteredBlock("furnace");
         LIT_FURNACE = getRegisteredBlock("lit_furnace");
         STANDING_SIGN = getRegisteredBlock("standing_sign");
         OAK_DOOR = (do)getRegisteredBlock("wooden_door");
         SPRUCE_DOOR = (do)getRegisteredBlock("spruce_door");
         BIRCH_DOOR = (do)getRegisteredBlock("birch_door");
         JUNGLE_DOOR = (do)getRegisteredBlock("jungle_door");
         ACACIA_DOOR = (do)getRegisteredBlock("acacia_door");
         DARK_OAK_DOOR = (do)getRegisteredBlock("dark_oak_door");
         LADDER = getRegisteredBlock("ladder");
         RAIL = getRegisteredBlock("rail");
         STONE_STAIRS = getRegisteredBlock("stone_stairs");
         WALL_SIGN = getRegisteredBlock("wall_sign");
         LEVER = getRegisteredBlock("lever");
         STONE_PRESSURE_PLATE = getRegisteredBlock("stone_pressure_plate");
         IRON_DOOR = (do)getRegisteredBlock("iron_door");
         WOODEN_PRESSURE_PLATE = getRegisteredBlock("wooden_pressure_plate");
         REDSTONE_ORE = getRegisteredBlock("redstone_ore");
         LIT_REDSTONE_ORE = getRegisteredBlock("lit_redstone_ore");
         UNLIT_REDSTONE_TORCH = getRegisteredBlock("unlit_redstone_torch");
         REDSTONE_TORCH = getRegisteredBlock("redstone_torch");
         STONE_BUTTON = getRegisteredBlock("stone_button");
         SNOW_LAYER = getRegisteredBlock("snow_layer");
         ICE = getRegisteredBlock("ice");
         SNOW = getRegisteredBlock("snow");
         CACTUS = (cN)getRegisteredBlock("cactus");
         CLAY = getRegisteredBlock("clay");
         REEDS = (gg)getRegisteredBlock("reeds");
         JUKEBOX = getRegisteredBlock("jukebox");
         OAK_FENCE = getRegisteredBlock("fence");
         SPRUCE_FENCE = getRegisteredBlock("spruce_fence");
         BIRCH_FENCE = getRegisteredBlock("birch_fence");
         JUNGLE_FENCE = getRegisteredBlock("jungle_fence");
         DARK_OAK_FENCE = getRegisteredBlock("dark_oak_fence");
         ACACIA_FENCE = getRegisteredBlock("acacia_fence");
         PUMPKIN = getRegisteredBlock("pumpkin");
         NETHERRACK = getRegisteredBlock("netherrack");
         SOUL_SAND = getRegisteredBlock("soul_sand");
         GLOWSTONE = getRegisteredBlock("glowstone");
         PORTAL = (fo)getRegisteredBlock("portal");
         LIT_PUMPKIN = getRegisteredBlock("lit_pumpkin");
         CAKE = getRegisteredBlock("cake");
         UNPOWERED_REPEATER = (ga)getRegisteredBlock("unpowered_repeater");
         POWERED_REPEATER = (ga)getRegisteredBlock("powered_repeater");
         TRAPDOOR = getRegisteredBlock("trapdoor");
         MONSTER_EGG = getRegisteredBlock("monster_egg");
         STONEBRICK = getRegisteredBlock("stonebrick");
         BROWN_MUSHROOM_BLOCK = getRegisteredBlock("brown_mushroom_block");
         RED_MUSHROOM_BLOCK = getRegisteredBlock("red_mushroom_block");
         IRON_BARS = getRegisteredBlock("iron_bars");
         GLASS_PANE = getRegisteredBlock("glass_pane");
         MELON_BLOCK = getRegisteredBlock("melon_block");
         PUMPKIN_STEM = getRegisteredBlock("pumpkin_stem");
         MELON_STEM = getRegisteredBlock("melon_stem");
         VINE = getRegisteredBlock("vine");
         OAK_FENCE_GATE = getRegisteredBlock("fence_gate");
         SPRUCE_FENCE_GATE = getRegisteredBlock("spruce_fence_gate");
         BIRCH_FENCE_GATE = getRegisteredBlock("birch_fence_gate");
         JUNGLE_FENCE_GATE = getRegisteredBlock("jungle_fence_gate");
         DARK_OAK_FENCE_GATE = getRegisteredBlock("dark_oak_fence_gate");
         ACACIA_FENCE_GATE = getRegisteredBlock("acacia_fence_gate");
         BRICK_STAIRS = getRegisteredBlock("brick_stairs");
         STONE_BRICK_STAIRS = getRegisteredBlock("stone_brick_stairs");
         MYCELIUM = (eJ)getRegisteredBlock("mycelium");
         WATERLILY = getRegisteredBlock("waterlily");
         NETHER_BRICK = getRegisteredBlock("nether_brick");
         NETHER_BRICK_FENCE = getRegisteredBlock("nether_brick_fence");
         NETHER_BRICK_STAIRS = getRegisteredBlock("nether_brick_stairs");
         NETHER_WART = getRegisteredBlock("nether_wart");
         ENCHANTING_TABLE = getRegisteredBlock("enchanting_table");
         BREWING_STAND = getRegisteredBlock("brewing_stand");
         CAULDRON = (cR)getRegisteredBlock("cauldron");
         END_PORTAL = getRegisteredBlock("end_portal");
         END_PORTAL_FRAME = getRegisteredBlock("end_portal_frame");
         END_STONE = getRegisteredBlock("end_stone");
         DRAGON_EGG = getRegisteredBlock("dragon_egg");
         REDSTONE_LAMP = getRegisteredBlock("redstone_lamp");
         LIT_REDSTONE_LAMP = getRegisteredBlock("lit_redstone_lamp");
         DOUBLE_WOODEN_SLAB = (gG)getRegisteredBlock("double_wooden_slab");
         WOODEN_SLAB = (gG)getRegisteredBlock("wooden_slab");
         COCOA = getRegisteredBlock("cocoa");
         SANDSTONE_STAIRS = getRegisteredBlock("sandstone_stairs");
         EMERALD_ORE = getRegisteredBlock("emerald_ore");
         ENDER_CHEST = getRegisteredBlock("ender_chest");
         TRIPWIRE_HOOK = (hv)getRegisteredBlock("tripwire_hook");
         TRIPWIRE = getRegisteredBlock("tripwire");
         EMERALD_BLOCK = getRegisteredBlock("emerald_block");
         SPRUCE_STAIRS = getRegisteredBlock("spruce_stairs");
         BIRCH_STAIRS = getRegisteredBlock("birch_stairs");
         JUNGLE_STAIRS = getRegisteredBlock("jungle_stairs");
         COMMAND_BLOCK = getRegisteredBlock("command_block");
         BEACON = (cA)getRegisteredBlock("beacon");
         COBBLESTONE_WALL = getRegisteredBlock("cobblestone_wall");
         FLOWER_POT = getRegisteredBlock("flower_pot");
         CARROTS = getRegisteredBlock("carrots");
         POTATOES = getRegisteredBlock("potatoes");
         WOODEN_BUTTON = getRegisteredBlock("wooden_button");
         SKULL = (gE)getRegisteredBlock("skull");
         ANVIL = getRegisteredBlock("anvil");
         TRAPPED_CHEST = getRegisteredBlock("trapped_chest");
         LIGHT_WEIGHTED_PRESSURE_PLATE = getRegisteredBlock("light_weighted_pressure_plate");
         HEAVY_WEIGHTED_PRESSURE_PLATE = getRegisteredBlock("heavy_weighted_pressure_plate");
         UNPOWERED_COMPARATOR = (fW)getRegisteredBlock("unpowered_comparator");
         POWERED_COMPARATOR = (fW)getRegisteredBlock("powered_comparator");
         DAYLIGHT_DETECTOR = (df)getRegisteredBlock("daylight_detector");
         DAYLIGHT_DETECTOR_INVERTED = (df)getRegisteredBlock("daylight_detector_inverted");
         REDSTONE_BLOCK = getRegisteredBlock("redstone_block");
         QUARTZ_ORE = getRegisteredBlock("quartz_ore");
         HOPPER = (em)getRegisteredBlock("hopper");
         QUARTZ_BLOCK = getRegisteredBlock("quartz_block");
         QUARTZ_STAIRS = getRegisteredBlock("quartz_stairs");
         ACTIVATOR_RAIL = getRegisteredBlock("activator_rail");
         DROPPER = getRegisteredBlock("dropper");
         STAINED_HARDENED_CLAY = getRegisteredBlock("stained_hardened_clay");
         BARRIER = getRegisteredBlock("barrier");
         IRON_TRAPDOOR = getRegisteredBlock("iron_trapdoor");
         HAY_BLOCK = getRegisteredBlock("hay_block");
         CARPET = getRegisteredBlock("carpet");
         HARDENED_CLAY = getRegisteredBlock("hardened_clay");
         COAL_BLOCK = getRegisteredBlock("coal_block");
         PACKED_ICE = getRegisteredBlock("packed_ice");
         ACACIA_STAIRS = getRegisteredBlock("acacia_stairs");
         DARK_OAK_STAIRS = getRegisteredBlock("dark_oak_stairs");
         SLIME_BLOCK = getRegisteredBlock("slime");
         DOUBLE_PLANT = (dr)getRegisteredBlock("double_plant");
         STAINED_GLASS = (gN)getRegisteredBlock("stained_glass");
         STAINED_GLASS_PANE = (gP)getRegisteredBlock("stained_glass_pane");
         PRISMARINE = getRegisteredBlock("prismarine");
         SEA_LANTERN = getRegisteredBlock("sea_lantern");
         STANDING_BANNER = getRegisteredBlock("standing_banner");
         WALL_BANNER = getRegisteredBlock("wall_banner");
         RED_SANDSTONE = getRegisteredBlock("red_sandstone");
         RED_SANDSTONE_STAIRS = getRegisteredBlock("red_sandstone_stairs");
         DOUBLE_STONE_SLAB2 = (gG)getRegisteredBlock("double_stone_slab2");
         STONE_SLAB2 = (gG)getRegisteredBlock("stone_slab2");
         END_ROD = getRegisteredBlock("end_rod");
         CHORUS_PLANT = getRegisteredBlock("chorus_plant");
         CHORUS_FLOWER = getRegisteredBlock("chorus_flower");
         PURPUR_BLOCK = getRegisteredBlock("purpur_block");
         PURPUR_PILLAR = getRegisteredBlock("purpur_pillar");
         PURPUR_STAIRS = getRegisteredBlock("purpur_stairs");
         PURPUR_DOUBLE_SLAB = (gG)getRegisteredBlock("purpur_double_slab");
         PURPUR_SLAB = (gG)getRegisteredBlock("purpur_slab");
         END_BRICKS = getRegisteredBlock("end_bricks");
         BEETROOTS = getRegisteredBlock("beetroots");
         GRASS_PATH = getRegisteredBlock("grass_path");
         END_GATEWAY = getRegisteredBlock("end_gateway");
         REPEATING_COMMAND_BLOCK = getRegisteredBlock("repeating_command_block");
         CHAIN_COMMAND_BLOCK = getRegisteredBlock("chain_command_block");
         FROSTED_ICE = getRegisteredBlock("frosted_ice");
         MAGMA = getRegisteredBlock("magma");
         NETHER_WART_BLOCK = getRegisteredBlock("nether_wart_block");
         RED_NETHER_BRICK = getRegisteredBlock("red_nether_brick");
         BONE_BLOCK = getRegisteredBlock("bone_block");
         STRUCTURE_VOID = getRegisteredBlock("structure_void");
         OBSERVER = getRegisteredBlock("observer");
         WHITE_SHULKER_BOX = getRegisteredBlock("white_shulker_box");
         ORANGE_SHULKER_BOX = getRegisteredBlock("orange_shulker_box");
         MAGENTA_SHULKER_BOX = getRegisteredBlock("magenta_shulker_box");
         LIGHT_BLUE_SHULKER_BOX = getRegisteredBlock("light_blue_shulker_box");
         YELLOW_SHULKER_BOX = getRegisteredBlock("yellow_shulker_box");
         LIME_SHULKER_BOX = getRegisteredBlock("lime_shulker_box");
         PINK_SHULKER_BOX = getRegisteredBlock("pink_shulker_box");
         GRAY_SHULKER_BOX = getRegisteredBlock("gray_shulker_box");
         SILVER_SHULKER_BOX = getRegisteredBlock("silver_shulker_box");
         CYAN_SHULKER_BOX = getRegisteredBlock("cyan_shulker_box");
         PURPLE_SHULKER_BOX = getRegisteredBlock("purple_shulker_box");
         BLUE_SHULKER_BOX = getRegisteredBlock("blue_shulker_box");
         BROWN_SHULKER_BOX = getRegisteredBlock("brown_shulker_box");
         GREEN_SHULKER_BOX = getRegisteredBlock("green_shulker_box");
         RED_SHULKER_BOX = getRegisteredBlock("red_shulker_box");
         BLACK_SHULKER_BOX = getRegisteredBlock("black_shulker_box");
         WHITE_GLAZED_TERRACOTTA = getRegisteredBlock("white_glazed_terracotta");
         ORANGE_GLAZED_TERRACOTTA = getRegisteredBlock("orange_glazed_terracotta");
         MAGENTA_GLAZED_TERRACOTTA = getRegisteredBlock("magenta_glazed_terracotta");
         LIGHT_BLUE_GLAZED_TERRACOTTA = getRegisteredBlock("light_blue_glazed_terracotta");
         YELLOW_GLAZED_TERRACOTTA = getRegisteredBlock("yellow_glazed_terracotta");
         LIME_GLAZED_TERRACOTTA = getRegisteredBlock("lime_glazed_terracotta");
         PINK_GLAZED_TERRACOTTA = getRegisteredBlock("pink_glazed_terracotta");
         GRAY_GLAZED_TERRACOTTA = getRegisteredBlock("gray_glazed_terracotta");
         SILVER_GLAZED_TERRACOTTA = getRegisteredBlock("silver_glazed_terracotta");
         CYAN_GLAZED_TERRACOTTA = getRegisteredBlock("cyan_glazed_terracotta");
         PURPLE_GLAZED_TERRACOTTA = getRegisteredBlock("purple_glazed_terracotta");
         BLUE_GLAZED_TERRACOTTA = getRegisteredBlock("blue_glazed_terracotta");
         BROWN_GLAZED_TERRACOTTA = getRegisteredBlock("brown_glazed_terracotta");
         GREEN_GLAZED_TERRACOTTA = getRegisteredBlock("green_glazed_terracotta");
         RED_GLAZED_TERRACOTTA = getRegisteredBlock("red_glazed_terracotta");
         BLACK_GLAZED_TERRACOTTA = getRegisteredBlock("black_glazed_terracotta");
         CONCRETE = getRegisteredBlock("concrete");
         CONCRETE_POWDER = getRegisteredBlock("concrete_powder");
         STRUCTURE_BLOCK = getRegisteredBlock("structure_block");
         CACHE.clear();
      }
   }
}
