package neo;

import net.minecraft.util.ResourceLocation;

public class NK {
   public static final OL AIR;
   public static final OL IRON_SHOVEL;
   public static final OL IRON_PICKAXE;
   public static final OL IRON_AXE;
   public static final OL FLINT_AND_STEEL;
   public static final OL APPLE;
   public static final Pd BOW;
   public static final OL ARROW;
   public static final OL SPECTRAL_ARROW;
   public static final OL TIPPED_ARROW;
   public static final OL COAL;
   public static final OL DIAMOND;
   public static final OL IRON_INGOT;
   public static final OL GOLD_INGOT;
   public static final OL IRON_SWORD;
   public static final OL WOODEN_SWORD;
   public static final OL WOODEN_SHOVEL;
   public static final OL WOODEN_PICKAXE;
   public static final OL WOODEN_AXE;
   public static final OL STONE_SWORD;
   public static final OL STONE_SHOVEL;
   public static final OL STONE_PICKAXE;
   public static final OL STONE_AXE;
   public static final OL DIAMOND_SWORD;
   public static final OL DIAMOND_SHOVEL;
   public static final OL DIAMOND_PICKAXE;
   public static final OL DIAMOND_AXE;
   public static final OL STICK;
   public static final OL BOWL;
   public static final OL MUSHROOM_STEW;
   public static final OL GOLDEN_SWORD;
   public static final OL GOLDEN_SHOVEL;
   public static final OL GOLDEN_PICKAXE;
   public static final OL GOLDEN_AXE;
   public static final OL STRING;
   public static final OL FEATHER;
   public static final OL GUNPOWDER;
   public static final OL WOODEN_HOE;
   public static final OL STONE_HOE;
   public static final OL IRON_HOE;
   public static final OL DIAMOND_HOE;
   public static final OL GOLDEN_HOE;
   public static final OL WHEAT_SEEDS;
   public static final OL WHEAT;
   public static final OL BREAD;
   public static final OR LEATHER_HELMET;
   public static final OR LEATHER_CHESTPLATE;
   public static final OR LEATHER_LEGGINGS;
   public static final OR LEATHER_BOOTS;
   public static final OR CHAINMAIL_HELMET;
   public static final OR CHAINMAIL_CHESTPLATE;
   public static final OR CHAINMAIL_LEGGINGS;
   public static final OR CHAINMAIL_BOOTS;
   public static final OR IRON_HELMET;
   public static final OR IRON_CHESTPLATE;
   public static final OR IRON_LEGGINGS;
   public static final OR IRON_BOOTS;
   public static final OR DIAMOND_HELMET;
   public static final OR DIAMOND_CHESTPLATE;
   public static final OR DIAMOND_LEGGINGS;
   public static final OR DIAMOND_BOOTS;
   public static final OR GOLDEN_HELMET;
   public static final OR GOLDEN_CHESTPLATE;
   public static final OR GOLDEN_LEGGINGS;
   public static final OR GOLDEN_BOOTS;
   public static final OL FLINT;
   public static final OL PORKCHOP;
   public static final OL COOKED_PORKCHOP;
   public static final OL PAINTING;
   public static final OL GOLDEN_APPLE;
   public static final OL SIGN;
   public static final OL OAK_DOOR;
   public static final OL SPRUCE_DOOR;
   public static final OL BIRCH_DOOR;
   public static final OL JUNGLE_DOOR;
   public static final OL ACACIA_DOOR;
   public static final OL DARK_OAK_DOOR;
   public static final OL BUCKET;
   public static final OL WATER_BUCKET;
   public static final OL LAVA_BUCKET;
   public static final OL MINECART;
   public static final OL SADDLE;
   public static final OL IRON_DOOR;
   public static final OL REDSTONE;
   public static final OL SNOWBALL;
   public static final OL BOAT;
   public static final OL SPRUCE_BOAT;
   public static final OL BIRCH_BOAT;
   public static final OL JUNGLE_BOAT;
   public static final OL ACACIA_BOAT;
   public static final OL DARK_OAK_BOAT;
   public static final OL LEATHER;
   public static final OL MILK_BUCKET;
   public static final OL BRICK;
   public static final OL CLAY_BALL;
   public static final OL REEDS;
   public static final OL PAPER;
   public static final OL BOOK;
   public static final OL SLIME_BALL;
   public static final OL CHEST_MINECART;
   public static final OL FURNACE_MINECART;
   public static final OL EGG;
   public static final OL COMPASS;
   public static final PG FISHING_ROD;
   public static final OL CLOCK;
   public static final OL GLOWSTONE_DUST;
   public static final OL FISH;
   public static final OL COOKED_FISH;
   public static final OL DYE;
   public static final OL BONE;
   public static final OL SUGAR;
   public static final OL CAKE;
   public static final OL BED;
   public static final OL REPEATER;
   public static final OL COOKIE;
   public static final PT FILLED_MAP;
   public static final Qk SHEARS;
   public static final OL MELON;
   public static final OL PUMPKIN_SEEDS;
   public static final OL MELON_SEEDS;
   public static final OL BEEF;
   public static final OL COOKED_BEEF;
   public static final OL CHICKEN;
   public static final OL COOKED_CHICKEN;
   public static final OL MUTTON;
   public static final OL COOKED_MUTTON;
   public static final OL RABBIT;
   public static final OL COOKED_RABBIT;
   public static final OL RABBIT_STEW;
   public static final OL RABBIT_FOOT;
   public static final OL RABBIT_HIDE;
   public static final OL ROTTEN_FLESH;
   public static final OL ENDER_PEARL;
   public static final OL BLAZE_ROD;
   public static final OL GHAST_TEAR;
   public static final OL GOLD_NUGGET;
   public static final OL NETHER_WART;
   public static final Qe POTIONITEM;
   public static final Qe SPLASH_POTION;
   public static final Qe LINGERING_POTION;
   public static final OL GLASS_BOTTLE;
   public static final OL DRAGON_BREATH;
   public static final OL SPIDER_EYE;
   public static final OL FERMENTED_SPIDER_EYE;
   public static final OL BLAZE_POWDER;
   public static final OL MAGMA_CREAM;
   public static final OL BREWING_STAND;
   public static final OL CAULDRON;
   public static final OL ENDER_EYE;
   public static final OL SPECKLED_MELON;
   public static final OL SPAWN_EGG;
   public static final OL EXPERIENCE_BOTTLE;
   public static final OL FIRE_CHARGE;
   public static final OL WRITABLE_BOOK;
   public static final OL WRITTEN_BOOK;
   public static final OL EMERALD;
   public static final OL ITEM_FRAME;
   public static final OL FLOWER_POT;
   public static final OL CARROT;
   public static final OL POTATO;
   public static final OL BAKED_POTATO;
   public static final OL POISONOUS_POTATO;
   public static final Pu MAP;
   public static final OL GOLDEN_CARROT;
   public static final OL SKULL;
   public static final OL CARROT_ON_A_STICK;
   public static final OL NETHER_STAR;
   public static final OL PUMPKIN_PIE;
   public static final OL FIREWORKS;
   public static final OL FIREWORK_CHARGE;
   public static final OL ENCHANTED_BOOK;
   public static final OL COMPARATOR;
   public static final OL NETHERBRICK;
   public static final OL QUARTZ;
   public static final OL TNT_MINECART;
   public static final OL HOPPER_MINECART;
   public static final OS ARMOR_STAND;
   public static final OL IRON_HORSE_ARMOR;
   public static final OL GOLDEN_HORSE_ARMOR;
   public static final OL DIAMOND_HORSE_ARMOR;
   public static final OL LEAD;
   public static final OL NAME_TAG;
   public static final OL COMMAND_BLOCK_MINECART;
   public static final OL RECORD_13;
   public static final OL RECORD_CAT;
   public static final OL RECORD_BLOCKS;
   public static final OL RECORD_CHIRP;
   public static final OL RECORD_FAR;
   public static final OL RECORD_MALL;
   public static final OL RECORD_MELLOHI;
   public static final OL RECORD_STAL;
   public static final OL RECORD_STRAD;
   public static final OL RECORD_WARD;
   public static final OL RECORD_11;
   public static final OL RECORD_WAIT;
   public static final OL PRISMARINE_SHARD;
   public static final OL PRISMARINE_CRYSTALS;
   public static final OL BANNER;
   public static final OL END_CRYSTAL;
   public static final OL SHIELD;
   public static final OL ELYTRA;
   public static final OL CHORUS_FRUIT;
   public static final OL CHORUS_FRUIT_POPPED;
   public static final OL BEETROOT_SEEDS;
   public static final OL BEETROOT;
   public static final OL BEETROOT_SOUP;
   public static final OL TOTEM_OF_UNDYING;
   public static final OL SHULKER_SHELL;
   public static final OL IRON_NUGGET;
   public static final OL KNOWLEDGE_BOOK;

   public NK() {
   }

   private static OL getRegisteredItem(String name) {
      OL item = (OL)OL.REGISTRY.getObject(new ResourceLocation(name));
      if (item == null) {
         throw new IllegalStateException("Invalid Item requested: " + name);
      } else {
         return item;
      }
   }

   static {
      if (!NI.isRegistered()) {
         throw new RuntimeException("Accessed Items before Bootstrap!");
      } else {
         AIR = getRegisteredItem("air");
         IRON_SHOVEL = getRegisteredItem("iron_shovel");
         IRON_PICKAXE = getRegisteredItem("iron_pickaxe");
         IRON_AXE = getRegisteredItem("iron_axe");
         FLINT_AND_STEEL = getRegisteredItem("flint_and_steel");
         APPLE = getRegisteredItem("apple");
         BOW = (Pd)getRegisteredItem("bow");
         ARROW = getRegisteredItem("arrow");
         SPECTRAL_ARROW = getRegisteredItem("spectral_arrow");
         TIPPED_ARROW = getRegisteredItem("tipped_arrow");
         COAL = getRegisteredItem("coal");
         DIAMOND = getRegisteredItem("diamond");
         IRON_INGOT = getRegisteredItem("iron_ingot");
         GOLD_INGOT = getRegisteredItem("gold_ingot");
         IRON_SWORD = getRegisteredItem("iron_sword");
         WOODEN_SWORD = getRegisteredItem("wooden_sword");
         WOODEN_SHOVEL = getRegisteredItem("wooden_shovel");
         WOODEN_PICKAXE = getRegisteredItem("wooden_pickaxe");
         WOODEN_AXE = getRegisteredItem("wooden_axe");
         STONE_SWORD = getRegisteredItem("stone_sword");
         STONE_SHOVEL = getRegisteredItem("stone_shovel");
         STONE_PICKAXE = getRegisteredItem("stone_pickaxe");
         STONE_AXE = getRegisteredItem("stone_axe");
         DIAMOND_SWORD = getRegisteredItem("diamond_sword");
         DIAMOND_SHOVEL = getRegisteredItem("diamond_shovel");
         DIAMOND_PICKAXE = getRegisteredItem("diamond_pickaxe");
         DIAMOND_AXE = getRegisteredItem("diamond_axe");
         STICK = getRegisteredItem("stick");
         BOWL = getRegisteredItem("bowl");
         MUSHROOM_STEW = getRegisteredItem("mushroom_stew");
         GOLDEN_SWORD = getRegisteredItem("golden_sword");
         GOLDEN_SHOVEL = getRegisteredItem("golden_shovel");
         GOLDEN_PICKAXE = getRegisteredItem("golden_pickaxe");
         GOLDEN_AXE = getRegisteredItem("golden_axe");
         STRING = getRegisteredItem("string");
         FEATHER = getRegisteredItem("feather");
         GUNPOWDER = getRegisteredItem("gunpowder");
         WOODEN_HOE = getRegisteredItem("wooden_hoe");
         STONE_HOE = getRegisteredItem("stone_hoe");
         IRON_HOE = getRegisteredItem("iron_hoe");
         DIAMOND_HOE = getRegisteredItem("diamond_hoe");
         GOLDEN_HOE = getRegisteredItem("golden_hoe");
         WHEAT_SEEDS = getRegisteredItem("wheat_seeds");
         WHEAT = getRegisteredItem("wheat");
         BREAD = getRegisteredItem("bread");
         LEATHER_HELMET = (OR)getRegisteredItem("leather_helmet");
         LEATHER_CHESTPLATE = (OR)getRegisteredItem("leather_chestplate");
         LEATHER_LEGGINGS = (OR)getRegisteredItem("leather_leggings");
         LEATHER_BOOTS = (OR)getRegisteredItem("leather_boots");
         CHAINMAIL_HELMET = (OR)getRegisteredItem("chainmail_helmet");
         CHAINMAIL_CHESTPLATE = (OR)getRegisteredItem("chainmail_chestplate");
         CHAINMAIL_LEGGINGS = (OR)getRegisteredItem("chainmail_leggings");
         CHAINMAIL_BOOTS = (OR)getRegisteredItem("chainmail_boots");
         IRON_HELMET = (OR)getRegisteredItem("iron_helmet");
         IRON_CHESTPLATE = (OR)getRegisteredItem("iron_chestplate");
         IRON_LEGGINGS = (OR)getRegisteredItem("iron_leggings");
         IRON_BOOTS = (OR)getRegisteredItem("iron_boots");
         DIAMOND_HELMET = (OR)getRegisteredItem("diamond_helmet");
         DIAMOND_CHESTPLATE = (OR)getRegisteredItem("diamond_chestplate");
         DIAMOND_LEGGINGS = (OR)getRegisteredItem("diamond_leggings");
         DIAMOND_BOOTS = (OR)getRegisteredItem("diamond_boots");
         GOLDEN_HELMET = (OR)getRegisteredItem("golden_helmet");
         GOLDEN_CHESTPLATE = (OR)getRegisteredItem("golden_chestplate");
         GOLDEN_LEGGINGS = (OR)getRegisteredItem("golden_leggings");
         GOLDEN_BOOTS = (OR)getRegisteredItem("golden_boots");
         FLINT = getRegisteredItem("flint");
         PORKCHOP = getRegisteredItem("porkchop");
         COOKED_PORKCHOP = getRegisteredItem("cooked_porkchop");
         PAINTING = getRegisteredItem("painting");
         GOLDEN_APPLE = getRegisteredItem("golden_apple");
         SIGN = getRegisteredItem("sign");
         OAK_DOOR = getRegisteredItem("wooden_door");
         SPRUCE_DOOR = getRegisteredItem("spruce_door");
         BIRCH_DOOR = getRegisteredItem("birch_door");
         JUNGLE_DOOR = getRegisteredItem("jungle_door");
         ACACIA_DOOR = getRegisteredItem("acacia_door");
         DARK_OAK_DOOR = getRegisteredItem("dark_oak_door");
         BUCKET = getRegisteredItem("bucket");
         WATER_BUCKET = getRegisteredItem("water_bucket");
         LAVA_BUCKET = getRegisteredItem("lava_bucket");
         MINECART = getRegisteredItem("minecart");
         SADDLE = getRegisteredItem("saddle");
         IRON_DOOR = getRegisteredItem("iron_door");
         REDSTONE = getRegisteredItem("redstone");
         SNOWBALL = getRegisteredItem("snowball");
         BOAT = getRegisteredItem("boat");
         SPRUCE_BOAT = getRegisteredItem("spruce_boat");
         BIRCH_BOAT = getRegisteredItem("birch_boat");
         JUNGLE_BOAT = getRegisteredItem("jungle_boat");
         ACACIA_BOAT = getRegisteredItem("acacia_boat");
         DARK_OAK_BOAT = getRegisteredItem("dark_oak_boat");
         LEATHER = getRegisteredItem("leather");
         MILK_BUCKET = getRegisteredItem("milk_bucket");
         BRICK = getRegisteredItem("brick");
         CLAY_BALL = getRegisteredItem("clay_ball");
         REEDS = getRegisteredItem("reeds");
         PAPER = getRegisteredItem("paper");
         BOOK = getRegisteredItem("book");
         SLIME_BALL = getRegisteredItem("slime_ball");
         CHEST_MINECART = getRegisteredItem("chest_minecart");
         FURNACE_MINECART = getRegisteredItem("furnace_minecart");
         EGG = getRegisteredItem("egg");
         COMPASS = getRegisteredItem("compass");
         FISHING_ROD = (PG)getRegisteredItem("fishing_rod");
         CLOCK = getRegisteredItem("clock");
         GLOWSTONE_DUST = getRegisteredItem("glowstone_dust");
         FISH = getRegisteredItem("fish");
         COOKED_FISH = getRegisteredItem("cooked_fish");
         DYE = getRegisteredItem("dye");
         BONE = getRegisteredItem("bone");
         SUGAR = getRegisteredItem("sugar");
         CAKE = getRegisteredItem("cake");
         BED = getRegisteredItem("bed");
         REPEATER = getRegisteredItem("repeater");
         COOKIE = getRegisteredItem("cookie");
         FILLED_MAP = (PT)getRegisteredItem("filled_map");
         SHEARS = (Qk)getRegisteredItem("shears");
         MELON = getRegisteredItem("melon");
         PUMPKIN_SEEDS = getRegisteredItem("pumpkin_seeds");
         MELON_SEEDS = getRegisteredItem("melon_seeds");
         BEEF = getRegisteredItem("beef");
         COOKED_BEEF = getRegisteredItem("cooked_beef");
         CHICKEN = getRegisteredItem("chicken");
         COOKED_CHICKEN = getRegisteredItem("cooked_chicken");
         MUTTON = getRegisteredItem("mutton");
         COOKED_MUTTON = getRegisteredItem("cooked_mutton");
         RABBIT = getRegisteredItem("rabbit");
         COOKED_RABBIT = getRegisteredItem("cooked_rabbit");
         RABBIT_STEW = getRegisteredItem("rabbit_stew");
         RABBIT_FOOT = getRegisteredItem("rabbit_foot");
         RABBIT_HIDE = getRegisteredItem("rabbit_hide");
         ROTTEN_FLESH = getRegisteredItem("rotten_flesh");
         ENDER_PEARL = getRegisteredItem("ender_pearl");
         BLAZE_ROD = getRegisteredItem("blaze_rod");
         GHAST_TEAR = getRegisteredItem("ghast_tear");
         GOLD_NUGGET = getRegisteredItem("gold_nugget");
         NETHER_WART = getRegisteredItem("nether_wart");
         POTIONITEM = (Qe)getRegisteredItem("potion");
         SPLASH_POTION = (Qe)getRegisteredItem("splash_potion");
         LINGERING_POTION = (Qe)getRegisteredItem("lingering_potion");
         GLASS_BOTTLE = getRegisteredItem("glass_bottle");
         DRAGON_BREATH = getRegisteredItem("dragon_breath");
         SPIDER_EYE = getRegisteredItem("spider_eye");
         FERMENTED_SPIDER_EYE = getRegisteredItem("fermented_spider_eye");
         BLAZE_POWDER = getRegisteredItem("blaze_powder");
         MAGMA_CREAM = getRegisteredItem("magma_cream");
         BREWING_STAND = getRegisteredItem("brewing_stand");
         CAULDRON = getRegisteredItem("cauldron");
         ENDER_EYE = getRegisteredItem("ender_eye");
         SPECKLED_MELON = getRegisteredItem("speckled_melon");
         SPAWN_EGG = getRegisteredItem("spawn_egg");
         EXPERIENCE_BOTTLE = getRegisteredItem("experience_bottle");
         FIRE_CHARGE = getRegisteredItem("fire_charge");
         WRITABLE_BOOK = getRegisteredItem("writable_book");
         WRITTEN_BOOK = getRegisteredItem("written_book");
         EMERALD = getRegisteredItem("emerald");
         ITEM_FRAME = getRegisteredItem("item_frame");
         FLOWER_POT = getRegisteredItem("flower_pot");
         CARROT = getRegisteredItem("carrot");
         POTATO = getRegisteredItem("potato");
         BAKED_POTATO = getRegisteredItem("baked_potato");
         POISONOUS_POTATO = getRegisteredItem("poisonous_potato");
         MAP = (Pu)getRegisteredItem("map");
         GOLDEN_CARROT = getRegisteredItem("golden_carrot");
         SKULL = getRegisteredItem("skull");
         CARROT_ON_A_STICK = getRegisteredItem("carrot_on_a_stick");
         NETHER_STAR = getRegisteredItem("nether_star");
         PUMPKIN_PIE = getRegisteredItem("pumpkin_pie");
         FIREWORKS = getRegisteredItem("fireworks");
         FIREWORK_CHARGE = getRegisteredItem("firework_charge");
         ENCHANTED_BOOK = getRegisteredItem("enchanted_book");
         COMPARATOR = getRegisteredItem("comparator");
         NETHERBRICK = getRegisteredItem("netherbrick");
         QUARTZ = getRegisteredItem("quartz");
         TNT_MINECART = getRegisteredItem("tnt_minecart");
         HOPPER_MINECART = getRegisteredItem("hopper_minecart");
         ARMOR_STAND = (OS)getRegisteredItem("armor_stand");
         IRON_HORSE_ARMOR = getRegisteredItem("iron_horse_armor");
         GOLDEN_HORSE_ARMOR = getRegisteredItem("golden_horse_armor");
         DIAMOND_HORSE_ARMOR = getRegisteredItem("diamond_horse_armor");
         LEAD = getRegisteredItem("lead");
         NAME_TAG = getRegisteredItem("name_tag");
         COMMAND_BLOCK_MINECART = getRegisteredItem("command_block_minecart");
         RECORD_13 = getRegisteredItem("record_13");
         RECORD_CAT = getRegisteredItem("record_cat");
         RECORD_BLOCKS = getRegisteredItem("record_blocks");
         RECORD_CHIRP = getRegisteredItem("record_chirp");
         RECORD_FAR = getRegisteredItem("record_far");
         RECORD_MALL = getRegisteredItem("record_mall");
         RECORD_MELLOHI = getRegisteredItem("record_mellohi");
         RECORD_STAL = getRegisteredItem("record_stal");
         RECORD_STRAD = getRegisteredItem("record_strad");
         RECORD_WARD = getRegisteredItem("record_ward");
         RECORD_11 = getRegisteredItem("record_11");
         RECORD_WAIT = getRegisteredItem("record_wait");
         PRISMARINE_SHARD = getRegisteredItem("prismarine_shard");
         PRISMARINE_CRYSTALS = getRegisteredItem("prismarine_crystals");
         BANNER = getRegisteredItem("banner");
         END_CRYSTAL = getRegisteredItem("end_crystal");
         SHIELD = getRegisteredItem("shield");
         ELYTRA = getRegisteredItem("elytra");
         CHORUS_FRUIT = getRegisteredItem("chorus_fruit");
         CHORUS_FRUIT_POPPED = getRegisteredItem("chorus_fruit_popped");
         BEETROOT_SEEDS = getRegisteredItem("beetroot_seeds");
         BEETROOT = getRegisteredItem("beetroot");
         BEETROOT_SOUP = getRegisteredItem("beetroot_soup");
         TOTEM_OF_UNDYING = getRegisteredItem("totem_of_undying");
         SHULKER_SHELL = getRegisteredItem("shulker_shell");
         IRON_NUGGET = getRegisteredItem("iron_nugget");
         KNOWLEDGE_BOOK = getRegisteredItem("knowledge_book");
      }
   }
}
